# .dependabot/config.yml
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    create-pull-requests: true
    merge-mode: "none"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    create-pull-requests: true
    merge-mode: "none"
