server:
  port: 8080
  address: 0.0.0.0


spring:
  main:
    banner-mode: "off"
  application:
    name: mythrium
  datasource:
    driver-class-name=org.postgresql.Driver
    url=jdbc:postgresql://localhost:5432/mythrium
    username=postgres
    password=admin
