spring:
  profiles:
    active: debug
  main:
    banner-mode: off
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mythrium
    username: postgres
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-dll: true
    show-sql: true
    hibernate:
      dll-auto: update


server:
  port: 8080
  address: 0.0.0.0
  compression:
    enabled: true
    mime-types: text/plain,text/html,text/css,application/javascript,application/json,application/xml,text/xml
    min-response-size: 10240