name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    # Install and setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Install dependencies
    - name: Install Dependencies
      run: npm ci

    # Build Vite in the ./frontend directory
    - name: Build Vite
      run: |
        cd frontend
        npm ci
        npm run build

    # Run the build step for the main project, if applicable
    - name: Build Main Project
      run: npm run build
